### PR TITLE
renderComponentToString api change

### PR DESCRIPTION
**Pull request by ndreckshage**
http://facebook.github.io/react/docs/top-level-api.html#react.rendercomponenttostring

### CODE REVIEW

**Comment by stefanRitter** [comment]
@ndreckshage have you signed the CLA in the meantime?

**Comment by ndreckshage** [comment]
Yup

**Comment by zpao** [comment]
The API has actually changed to just `React.renderToString` in the months since (http://facebook.github.io/react/blog/2014/10/16/react-v0.12-rc1.html#renamed-apis). `renderComponentToString` will no longer work in v0.13 and moving forward.

**Comment by zpao** [comment]
Closing in favor of #3

**Pull request closed without merging**
